In [1]:
import pandas as pd         # Veri çerçeveli (DataFrame) işlemleri için
import numpy as np          # Sayısal işlemler için
import matplotlib.pyplot as plt     # Görselleştirme için
import seaborn as sns       # İleri düzey görselleştirme için
# Veri setini eğitim ve test olarak bölmek için
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler      # Veriyi ölçeklendirmek için
# Lojistik regresyon modeli için
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier       # Karar ağacı modeli için
from sklearn.ensemble import RandomForestClassifier   # Rastgele orman modeli için
# Performans metrikleri için
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

In [2]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test_x.csv")

In [16]:
train_data.head()

,index,Cinsiyet,Yıllık Ortalama Gelir,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Öbek İsmi,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Grubu_18-30,Yaş Grubu_31-40,Yaş Grubu_41-50,...,İstihdam Durumu_Emekli,İstihdam Durumu_Kendi İşinin Sahibi,İstihdam Durumu_İşsiz veya Düzenli Bir İşi Yok,Eğitime Devam Etme Durumu_Ediyor,Eğitime Devam Etme Durumu_Etmiyor,En Çok İlgilendiği Ürün Grubu_Elektronik ve Teknolojik Ürünler,En Çok İlgilendiği Ürün Grubu_Ev ve Mobilya,En Çok İlgilendiği Ürün Grubu_Giyim,En Çok İlgilendiği Ürün Grubu_Kozmetik,En Çok İlgilendiği Ürün Grubu_Spor Malzemeleri
0,0,0,748266.440879,32010.900881,37.310644,obek_4,102.936904,False,True,False,...,False,False,False,False,True,True,False,False,False,False
1,1,1,246298.609605,4145.729891,11.554851,obek_5,82.176053,False,False,False,...,False,True,False,False,True,False,False,False,False,True
2,2,1,268582.732360,9924.379414,55.353236,obek_8,141.661426,True,False,False,...,False,False,False,True,False,False,False,True,False,False
3,3,1,327721.837865,6417.780714,15.417239,obek_3,17.097397,False,False,False,...,False,True,False,False,True,False,False,True,False,False
4,4,1,397431.626948,7886.663061,14.689837,obek_3,20.470459,False,True,False,...,False,False,True,False,True,False,False,True,False,False

In [15]:
test_data.head()

,index,Cinsiyet,Yıllık Ortalama Gelir,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Grubu_18-30,Yaş Grubu_31-40,Yaş Grubu_41-50,Yaş Grubu_51-60,...,İstihdam Durumu_Emekli,İstihdam Durumu_Kendi İşinin Sahibi,İstihdam Durumu_İşsiz veya Düzenli Bir İşi Yok,Eğitime Devam Etme Durumu_Ediyor,Eğitime Devam Etme Durumu_Etmiyor,En Çok İlgilendiği Ürün Grubu_Elektronik ve Teknolojik Ürünler,En Çok İlgilendiği Ürün Grubu_Ev ve Mobilya,En Çok İlgilendiği Ürün Grubu_Giyim,En Çok İlgilendiği Ürün Grubu_Kozmetik,En Çok İlgilendiği Ürün Grubu_Spor Malzemeleri
0,0,1,365331.930346,5566.587664,15.442635,19.646460,False,False,False,True,...,False,False,False,False,True,False,False,True,False,False
1,1,1,414899.236174,6756.766203,14.957246,19.675863,False,False,True,False,...,False,False,True,False,True,False,False,False,False,True
2,2,0,152825.872271,4493.915682,10.907930,46.904518,False,False,False,False,...,False,False,True,False,True,False,False,True,False,False
3,3,0,489052.908472,42670.646595,32.333021,48.083609,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False
4,4,1,323635.711534,5959.266948,4.519968,12.752491,True,False,False,False,...,False,True,False,False,True,False,False,True,False,False

In [5]:
train_data["Cinsiyet"] = train_data["Cinsiyet"].replace(["Erkek"], 1)

In [6]:
train_data["Cinsiyet"] = train_data["Cinsiyet"].replace(["Kadın"], 0)

In [7]:
train_data.head()

,index,Cinsiyet,Yaş Grubu,Medeni Durum,Eğitim Düzeyi,İstihdam Durumu,Yıllık Ortalama Gelir,Yaşadığı Şehir,En Çok İlgilendiği Ürün Grubu,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Eğitime Devam Etme Durumu,Öbek İsmi,Yıllık Ortalama Sepete Atılan Ürün Adedi
0,0,0,31-40,Bekar,Yüksek Lisans Mezunu,Düzenli ve Ücretli Bir İşi Var,748266.440879,Büyük Şehir,Elektronik ve Teknolojik Ürünler,32010.900881,37.310644,Etmiyor,obek_4,102.936904
1,1,1,>60,Evli,Lise Mezunu,Kendi İşinin Sahibi,246298.609605,Küçük Şehir,Spor Malzemeleri,4145.729891,11.554851,Etmiyor,obek_5,82.176053
2,2,1,18-30,Bekar,Lise Mezunu,Düzenli ve Ücretli Bir İşi Var,268582.732360,Küçük Şehir,Giyim,9924.379414,55.353236,Ediyor,obek_8,141.661426
3,3,1,51-60,Evli,Lise Mezunu,Kendi İşinin Sahibi,327721.837865,Kırsal,Giyim,6417.780714,15.417239,Etmiyor,obek_3,17.097397
4,4,1,31-40,Evli,Ortaokul Mezunu,İşsiz veya Düzenli Bir İşi Yok,397431.626948,Büyük Şehir,Giyim,7886.663061,14.689837,Etmiyor,obek_3,20.470459

In [8]:
train_data = pd.get_dummies(train_data, columns=['Yaş Grubu', 'Medeni Durum', 'Eğitim Düzeyi',
                            'Yaşadığı Şehir', 'İstihdam Durumu', 'Eğitime Devam Etme Durumu', 'En Çok İlgilendiği Ürün Grubu'])

In [9]:
train_data

,index,Cinsiyet,Yıllık Ortalama Gelir,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Öbek İsmi,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Grubu_18-30,Yaş Grubu_31-40,Yaş Grubu_41-50,...,İstihdam Durumu_Emekli,İstihdam Durumu_Kendi İşinin Sahibi,İstihdam Durumu_İşsiz veya Düzenli Bir İşi Yok,Eğitime Devam Etme Durumu_Ediyor,Eğitime Devam Etme Durumu_Etmiyor,En Çok İlgilendiği Ürün Grubu_Elektronik ve Teknolojik Ürünler,En Çok İlgilendiği Ürün Grubu_Ev ve Mobilya,En Çok İlgilendiği Ürün Grubu_Giyim,En Çok İlgilendiği Ürün Grubu_Kozmetik,En Çok İlgilendiği Ürün Grubu_Spor Malzemeleri
0,0,0,748266.440879,32010.900881,37.310644,obek_4,102.936904,False,True,False,...,False,False,False,False,True,True,False,False,False,False
1,1,1,246298.609605,4145.729891,11.554851,obek_5,82.176053,False,False,False,...,False,True,False,False,True,False,False,False,False,True
2,2,1,268582.732360,9924.379414,55.353236,obek_8,141.661426,True,False,False,...,False,False,False,True,False,False,False,True,False,False
3,3,1,327721.837865,6417.780714,15.417239,obek_3,17.097397,False,False,False,...,False,True,False,False,True,False,False,True,False,False
4,4,1,397431.626948,7886.663061,14.689837,obek_3,20.470459,False,True,False,...,False,False,True,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5455,5455,0,478054.247819,43182.299801,31.356284,obek_6,51.600436,False,False,False,...,True,False,False,False,True,False,False,False,True,False
5456,5456,1,481852.853651,42107.996193,26.288620,obek_6,49.190536,False,False,False,...,False,True,False,False,True,False,True,False,False,False
5457,5457,0,309443.687351,4655.392445,5.156906,obek_1,9.537384,False,False,False,...,False,False,False,False,True,False,True,False,False,False
5458,5458,0,266604.268016,9016.165906,39.205399,obek_8,143.281718,True,False,False,...,False,False,False,True,False,False,True,False,False,False
5459,5459,1,276155.078333,9455.657480,50.554188,obek_8,127.329348,True,False,False,...,False,False,False,True,False,False,False,False,False,True

In [10]:
test_data["Cinsiyet"] = test_data["Cinsiyet"].replace(["Erkek"], 1)

In [11]:
test_data["Cinsiyet"] = test_data["Cinsiyet"].replace(["Kadın"], 0)

In [12]:
test_data = pd.get_dummies(test_data, columns=['Yaş Grubu', 'Medeni Durum', 'Eğitim Düzeyi',
                           'Yaşadığı Şehir', 'İstihdam Durumu', 'Eğitime Devam Etme Durumu', 'En Çok İlgilendiği Ürün Grubu'])

In [13]:
test_data

,index,Cinsiyet,Yıllık Ortalama Gelir,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Grubu_18-30,Yaş Grubu_31-40,Yaş Grubu_41-50,Yaş Grubu_51-60,...,İstihdam Durumu_Emekli,İstihdam Durumu_Kendi İşinin Sahibi,İstihdam Durumu_İşsiz veya Düzenli Bir İşi Yok,Eğitime Devam Etme Durumu_Ediyor,Eğitime Devam Etme Durumu_Etmiyor,En Çok İlgilendiği Ürün Grubu_Elektronik ve Teknolojik Ürünler,En Çok İlgilendiği Ürün Grubu_Ev ve Mobilya,En Çok İlgilendiği Ürün Grubu_Giyim,En Çok İlgilendiği Ürün Grubu_Kozmetik,En Çok İlgilendiği Ürün Grubu_Spor Malzemeleri
0,0,1,365331.930346,5566.587664,15.442635,19.646460,False,False,False,True,...,False,False,False,False,True,False,False,True,False,False
1,1,1,414899.236174,6756.766203,14.957246,19.675863,False,False,True,False,...,False,False,True,False,True,False,False,False,False,True
2,2,0,152825.872271,4493.915682,10.907930,46.904518,False,False,False,False,...,False,False,True,False,True,False,False,True,False,False
3,3,0,489052.908472,42670.646595,32.333021,48.083609,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False
4,4,1,323635.711534,5959.266948,4.519968,12.752491,True,False,False,False,...,False,True,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,2335,0,259190.078834,9559.156534,41.883661,117.627785,True,False,False,False,...,False,True,False,True,False,False,True,False,False,False
2336,2336,0,194580.563177,4070.232154,20.082996,45.659622,False,True,False,False,...,False,False,True,False,True,False,True,False,False,False
2337,2337,1,357730.521969,22589.204381,18.922305,100.691379,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2338,2338,1,213179.637202,4205.390562,10.758108,97.778913,True,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2339,2339,1,519013.573683,42675.353591,30.826534,39.657830,False,False,False,True,...,False,False,False,True,False,True,False,False,False,False